### ISSUE TITLE
It crashes when using the program on any midi that I've tried.

### ISSUE THREAD

**Issue by ValleyKnight** [Gnumaru/mididump#1]
Here is the error message.

Unhandled Exception: System.FormatException: End Track event was not the last MIDI event on track 0 at NAudio.Midi.MidiFile..ctor(Stream inputStream, Boolean strictChecking, Boolean ownInputStream)at mididump.MainClass.Main(String[] args)

**Comment by ValleyKnight** [comment]
Here's another error message I got.

Unhandled Exception: System.FormatException: Got an off without an on 94080 Note
Off Ch: 8 D7 Vel:0
   at NAudio.Midi.MidiFile.FindNoteOn(NoteEvent offEvent, List`1 outstandingNote
Ons)
   at NAudio.Midi.MidiFile..ctor(Stream inputStream, Boolean strictChecking, Boo
lean ownInputStream)
   at mididump.MainClass.Main(String[] args)
